name: 🛡 Specs

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  specs:
    name: Specs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          cache-version: 1

      - name: Run tests
        run: bundle exec rake spec
